export const adminActions = {
  FETCH_USER_SUCCESSFUL: "FETCH_USER_SUCCESSFUL",
  FETCH_USER_IN_PROGRESS: "FETCH_USER_IN_PROGRESS",
  FETCH_USER_FAILED: "FETCH_USER_FAILED",

  FETCH_USERS_SUCCESSFUL: "FETCH_USERS_SUCCESSFUL",
  FETCH_USERS_IN_PROGRESS: "FETCH_USERS_IN_PROGRESS",
  FETCH_USERS_FAILED: "FETCH_USERS_FAILED",

  DELETE_USER_SUCCESSFUL: "DELETE_USER_SUCCESSFUL",
  DELETE_USER_IN_PROGRESS: "DELETE_USER_IN_PROGRESS",
  DELETE_USER_FAILED: "DELETE_USER_FAILED",

  UPDATE_USER_SUCCESSFUL: "UPDATE_USER_SUCCESSFUL",
  UPDATE_USER_IN_PROGRESS: "UPDATE_USER_IN_PROGRESS",
  UPDATE_USER_FAILED: "UPDATE_USER_FAILED"
};
