export const authActions = {
  SIGNIN_SUCCESSFUL: "SIGNIN_SUCCESSFUL",
  SIGNIN_IN_PROGRESS: "SIGNIN_IN_PROGRESS",
  SIGNIN_FAILED: "SIGNIN_FAILED",

  VERIFY_TOKEN_SUCCESSFUL: "VERIFY_TOKEN_SUCCESSFUL",
  VERIFY_TOKEN_IN_PROGRESS: "VERIFY_TOKEN_IN_PROGRESS",
  VERIFY_TOKEN_FAILED: "VERIFY_TOKEN_FAILED",

  SIGNUP_SUCCESSFUL: "SIGNUP_SUCCESSFUL",
  SIGNUP_IN_PROGRESS: "SIGNUP_IN_PROGRESS",
  SIGNUP_FAILED: "SIGNUP_FAILED",

  UPDATE_SUCCESSFUL: "UPDATE_SUCCESSFUL",
  UPDATE_IN_PROGRESS: "UPDATE_IN_PROGRESS",
  UPDATE_FAILED: "UPDATE_FAILED",

  SIGNOUT: "SIGNOUT"
};
