export const authActions = {
  SIGNIN_SUCCESSFUL: "USER_SIGNIN_SUCCESSFUL",
  SIGNIN_IN_PROGRESS: "USER_SIGNIN_IN_PROGRESS",
  SIGNIN_FAILED: "USER_SIGNIN_FAILED",
  SIGNUP_SUCCESSFUL: "USER_SIGNUP_SUCCESSFUL",
  SIGNUP_IN_PROGRESS: "USER_SIGNUP_IN_PROGRESS",
  SIGNUP_FAILED: "USER_SIGNUP_FAILED",
  SIGNOUT: "SIGNOUT"
};
